### PR TITLE
Added .crx and .pem files

### PR DESCRIPTION
**Pull request by lalitmee**

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
Are you sure that every line starts with a `+`?

**Comment by lalitmee** [comment]
Actually, I created these files following the [link](https://developer.chrome.com/apps/packaging) which I have given on the issue. The process has created these files and I didn't change anything. So I am sure this would be it.

**Comment by aashutoshrathi** [comment]
So, its just that after this one need to download crx file and drag and drop it? and what is pem file for?

**Comment by lalitmee** [comment]
It's like, if you are creating the `crx` file for the first time, the process will create the file without demanding `pem` and it will also create a `pem` file which is a private key. But if you have created the `crx` before and now you want to update it, you must have a pem file related to the extension, the process will demand the `pem` file(private key) for updating the `crx` file.  

I think you will understand more about this on this [link](https://developer.chrome.com/apps/packaging).

**Comment by aashutoshrathi** [comment]
Should .pem files be open?

**Pull request merged**
