### PR TITLE
Download Dp button count and alignment of user's DP is fixed

### PR DESCRIPTION
**Pull request by lalitmee**
Sorry for these many changes. Actually, I use Prettier to format my code.

But I have fixed the bug of three buttons for `Download Dp` and alignment of `User's Dp`.

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
@lalitmee Can you lint the code using ESLint?

We already have a eslintrc file defined in the repo.
Thanks

**Comment by lalitmee** [comment]
@aashutoshrathi, one thing I am not getting that why there are two `eslintrc` files. I think only one will be enough.

**Comment by aashutoshrathi** [comment]
Yes, I think.
But please indent using eslint, so that we have not `;` in code.

**Comment by lalitmee** [comment]
Ok so I will edit `eslintrc` and will put the configuration for `;` not to put in the code.

**Comment by aashutoshrathi** [comment]
No. it's already configured just run 
```
npm i
./node_modules/.bin/eslint --fix
```

**Comment by lalitmee** [comment]
It's not configured with `Prettier`. :thinking:

**Comment by leventdeniz** [comment]
Quick question: Does commit 58d5d90 fix issue #16 ?

**Comment by lalitmee** [comment]
Hey @aashutoshrathi, here is a gif of current implementation what I have fixed and I think it's working. Please have a look. 

peek 2018-12-21 23-03

I would like to tell you one thing that `Download Dp` button comes on the load only for the first post and then you have to scroll down a bit then it will come for others.

**Comment by aashutoshrathi** [comment]
Sure, sir.
Will have a look.
Thanks

**Comment by aashutoshrathi** [comment]
Can we just fix the need of too much scroll?

**Comment by lalitmee** [comment]
Actually I haven't looked in that but I am also wondering that for 1st post it is coming right away but not for others.

**Pull request merged**
